# @author: Roy Meoded
# @date: 27.08.2026
# @description: Pydantic request/response schemas for the feedback endpoints.

"""
Pydantic schemas for thumbs-up / thumbs-down feedback.

There is no `user_id` field on `FeedbackCreate` on purpose: ownership must
come from the authenticated request (the JWT), never from a value the
frontend sends -- see CLAUDE.md's feedback rules.

Content-key convention (documented decision -- see
Skills/manage-content-feedback/SKILLS.md):

    market_news -> news:<data_source>:<article-id>
    coin_prices -> prices:<sorted-asset-ids>:<date>      (whole section, not per-coin)
    ai_insight  -> insight:<daily-insight-id>             (only for a saved, non-fallback insight)
    crypto_meme -> meme:<meme-id>

All four keys are generated by the backend (app/services/market_service.py,
insight_service.py, meme_service.py) and returned as part of each
section's own response -- the frontend never builds one itself.
"""
import re
from datetime import datetime
from typing import Literal

from pydantic import BaseModel, ConfigDict, field_validator

from app.core.constants import SECTION_TYPES

_SECTION_KEY_PREFIXES = {
    "market_news": "news:",
    "coin_prices": "prices:",
    "ai_insight": "insight:",
    "crypto_meme": "meme:",
}

_VALID_CONTENT_KEY = re.compile(r"^[A-Za-z0-9:_,.\-]+$")
_MAX_CONTENT_KEY_LENGTH = 255


class FeedbackCreate(BaseModel):
    section_type: str
    content_key: str
    vote: Literal[1, -1]

    @field_validator("section_type")
    @classmethod
    def validate_section_type(cls, value: str) -> str:
        if value not in SECTION_TYPES:
            raise ValueError(f"Unsupported section type: {value}")
        return value

    @field_validator("content_key")
    @classmethod
    def validate_content_key(cls, value: str) -> str:
        if not value or not value.strip():
            raise ValueError("content_key must not be blank")
        if len(value) > _MAX_CONTENT_KEY_LENGTH:
            raise ValueError(f"content_key must be at most {_MAX_CONTENT_KEY_LENGTH} characters")
        if not _VALID_CONTENT_KEY.match(value):
            raise ValueError("content_key contains unsupported characters")
        return value

    def validate_prefix_matches_section(self) -> None:
        """Called from the service layer (after both fields are already
        individually valid) since a cross-field check needs both values."""
        expected_prefix = _SECTION_KEY_PREFIXES[self.section_type]
        if not self.content_key.startswith(expected_prefix):
            raise ValueError(f"content_key for section '{self.section_type}' must start with '{expected_prefix}'")


class FeedbackResponse(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    section_type: str
    content_key: str
    vote: int
    updated_at: datetime
